server:
  port: 8082
  
spring:  datasource:    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: microservice
    password: microservice
      jpa:    hibernate:      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  application:
    name: HOTEL-SERVICE
       
       
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka